### ISSUE TITLE
Finaliza el turno sin jugada

### ISSUE THREAD

**Issue by beelanselm** [CacoRod/2048_Game#22]
Proyecto: 2048
Versión: 1
Plataforma: PC - Windows 64 bits
Título: Finaliza el turno sin jugada
Descripción: Cuando no se puede sumar ninguna casilla en una dirección, se pasa al turno, y se agrega otra casilla. No debería pasar esto. Debería advertirte que no hiciste ninguna movida y esperar a que hagas una para cambiar al turno del siguiente jugador.

**Comment by CacoRod** [comment]
corregido desde ver 1.01
