### ISSUE TITLE
Falta de color que permita mejor visualización de tableros

### ISSUE THREAD

**Issue by beelanselm** [CacoRod/2048_Game#23]
Proyecto: 2048
Versión: 1
Plataforma: PC - Windows 64 bits
Título: Falta de color que permita mejor visualización de tableros
Descripción: Los numeros nuevos deberian aparecer con un color distinto para una mejor visualización y el tablero del player 1 podria tener un color y el del player 2 otro para que no haya confusión.

**Comment by CacoRod** [comment]
Como nuestro juego es por consola. Carece de opciones de visualización.
