### ISSUE TITLE
El juego podria estar en español tambien

### ISSUE THREAD

**Issue by diegomoran777** [CacoRod/2048_Game#25]
Proyecto: 2048
Version: 1.01
Plataforma: Pc - Windows 10 64b -8 gb ram
Gravedad: trivial- min
Descripcion: Podria estar en ambos idiomas 
Paso a paso: al comenzar el juego no hay eleccion de idiomas
Tasa de reproduccion:100%

**Comment by CacoRod** [comment]
opcion para cambiar de idioma añadida en la version 1.10
