### ISSUE TITLE
los bloqueos estan del mismo color

### ISSUE THREAD

**Issue by diegomoran777** [CacoRod/2048_Game#26]
Proyecto: 2048
Version: 1.01
Plataforma: Pc - Windows 10 64bits 8gb ram
Gravedad: trivial- min
Descripcion:  el bloqueo es del mismo color que el resto-podria ser de otro color para identificarlo
Paso a paso: en el transcurso del juego aparece un numero en el tablero, movevs hacia una direccion, aparece otro numero y en algun momento aparece el bloqueo de color blanco.
Tasa de reproduccion:100%

**Comment by franciscoMigliardi24** [comment]
el juego es por consola, por este motivo no pueden aparecer colores, solo B&W
