### ISSUE TITLE
Partidas interminables

### ISSUE THREAD

**Issue by andreslcm** [CacoRod/2048_Game#27]
Juego: 248
SO: Windows 10 64 bits
Descripción: las partidas se hacen interminables
Tasa de reproducción: 100 %

**Comment by franciscoMigliardi24** [comment]
quise cerrar el issue, mala mia

**Comment by CacoRod** [comment]
Desde la version 1.15 se puede seleccionar un modo de juego alternativo en basado en puntaje. Es posible customizar la cantidad de puntaje y asi obtener partidas mas cortas
