### ISSUE TITLE
Juego e instrucciones por separado.

### ISSUE THREAD

**Issue by federicofranco97** [CacoRod/2048_Game#34]
Proyecto: 2048
Version: 1
Plataforma: Pc - Windows 10 64b
Gravedad: min
Descripcion: Hay un instructivo de como jugar pero viene separado del juego. Es impractico y si por error el usuario pierde o borra el txt no tiene mas acceso a las instrucciones.
Tasa de reproduccion: 100%

**Comment by CacoRod** [comment]
Las instrucciones de como jugar se encuentran en español e ingles en la pantalla del menu del juego y puedes remitirte a ellas presionando la tecla "h"
