### ISSUE TITLE
Idioma del juego.

### ISSUE THREAD

**Issue by federicofranco97** [CacoRod/2048_Game#35]
Proyecto: 2048
Version: 1
Plataforma: Pc - Windows 10 64b
Gravedad: min
Descripcion:
Paso a paso: El juego viene solamente en un idioma, ingles. Y contiene mucho texto, no es solamente la descripcion de un boton lo cual reduce la cantidad de usuarios a solamente aquellos que sepan el idioma.

**Comment by CacoRod** [comment]
Español fue agregado en la versión 1.10. Al momento de escribir esto el juego se encuentra en la versión 1.18.
