### ISSUE TITLE
No muestra mensaje de error cuando se ingresa un comando invalido.

### ISSUE THREAD

**Issue by federicofranco97** [CacoRod/2048_Game#36]
Proyecto: 2048
Version: 1
Plataforma: Pc - Windows 10 64b
Gravedad: medium
Descripcion: Si se tipea un comando invalido el juego ignora dicho input y no tira ningun mensaje de contenido invalido.
Paso a paso:
1.Abrir un juego
2.Tipear xxxxx y apretar enter.
Tasa de reproduccion: 100%

**Comment by CacoRod** [comment]
arreglado en la versión 1.01. Actualmente el juego se encuentra en la versión 1.18
