### ISSUE TITLE
Por cada movimiento hay que apretar enter.

### ISSUE THREAD

**Issue by federicofranco97** [CacoRod/2048_Game#37]
Proyecto: 2048
Version: 1
Plataforma: Pc - Windows 10 64b
Gravedad: medium
Descripcion: Cada vez que se hace un movimiento hay que presionar la tecla enter para que el programa reconozca el movimiento. En vez se podria poner un action listener que cuando se presione una tecla el juego valide la tecla y de ser valida ejecute la accion correspondiente.
Paso a paso:
1.Abrir un juego
2.Apretar cualquier tecla valida 
3.Presionar enter
Tasa de reproduccion: 100%

**Comment by CacoRod** [comment]
Debido a que el juego es por consola, el action listener no es una opción
