### ISSUE TITLE
Permite ingresar dos comandos al mismo tiempo.

### ISSUE THREAD

**Issue by federicofranco97** [CacoRod/2048_Game#38]
Proyecto: 2048
Version: 1
Plataforma: Pc - Windows 10 64b
Gravedad: max
Descripcion: El juego permite ingresar mas de un comando simultaneamente y no lo reporta como movimiento invalido.
Paso a paso:
1.Abrir un juego
2.Presionar la tecla w+a+w+a+w+a
3.Presionar enter
Tasa de reproduccion: 100%

**Comment by CacoRod** [comment]
efectivamente, el programa solo reconoce el primer carácter de el input
