### ISSUE TITLE
apretas N y no hace nada

### ISSUE THREAD

**Issue by diegomoran777** [CacoRod/2048_Game#39]
Proyecto: 2048
Version: 1.10
Plataforma: Pc - Windows 10 64bits 8 gb ram
Gravedad: medium
Descripcion: apretando la tecla N no hace nada
Paso a paso: en la partida, en el transcurso de la partida, apretar N no hace nada.
Tasa de reproduccion: 100%

**Comment by CacoRod** [comment]
arreglado en la version 1.18
